// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using answer_ua.Data;

#nullable disable

namespace AnswerUA.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20251105221948_FixRelations")]
    partial class FixRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("AnswerUA.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("AnswerUA.Models.BrandTargetCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCategoriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandsId");

                    b.HasIndex("TargetCategoriesId");

                    b.ToTable("BrandTargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("AnswerUA.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AnswerUA.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnswerUA.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubcategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCategoriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandsId");

                    b.HasIndex("ProductTypesId");

                    b.HasIndex("SubcategoriesId");

                    b.HasIndex("TargetCategoriesId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AnswerUA.Models.ProductColors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("AnswerUA.Models.ProductSizes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("AnswerUA.Models.ProductTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("AnswerUA.Models.Subcategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCategoriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProductTypesId");

                    b.HasIndex("TargetCategoriesId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("AnswerUA.Models.TargetCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.TargetCategoryProductType", b =>
                {
                    b.Property<int>("TargetCategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TargetCategoriesId", "ProductTypesId");

                    b.HasIndex("ProductTypesId");

                    b.ToTable("TargetCategoryProductType");
                });

            modelBuilder.Entity("AnswerUA.Models.BrandTargetCategories", b =>
                {
                    b.HasOne("AnswerUA.Models.Brand", "Brands")
                        .WithMany("BrandTargetCategories")
                        .HasForeignKey("BrandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.TargetCategories", "TargetCategories")
                        .WithMany()
                        .HasForeignKey("TargetCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brands");

                    b.Navigation("TargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.OrderItems", b =>
                {
                    b.HasOne("AnswerUA.Models.Orders", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AnswerUA.Models.Product", b =>
                {
                    b.HasOne("AnswerUA.Models.Brand", "Brands")
                        .WithMany()
                        .HasForeignKey("BrandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.ProductTypes", "ProductTypes")
                        .WithMany()
                        .HasForeignKey("ProductTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.Subcategories", "Subcategories")
                        .WithMany("Product")
                        .HasForeignKey("SubcategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.TargetCategories", "TargetCategories")
                        .WithMany()
                        .HasForeignKey("TargetCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brands");

                    b.Navigation("ProductTypes");

                    b.Navigation("Subcategories");

                    b.Navigation("TargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.Subcategories", b =>
                {
                    b.HasOne("AnswerUA.Models.Gender", "Genders")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("AnswerUA.Models.ProductTypes", "ProductTypes")
                        .WithMany("Subcategories")
                        .HasForeignKey("ProductTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.TargetCategories", "TargetCategories")
                        .WithMany()
                        .HasForeignKey("TargetCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genders");

                    b.Navigation("ProductTypes");

                    b.Navigation("TargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.TargetCategoryProductType", b =>
                {
                    b.HasOne("AnswerUA.Models.ProductTypes", "ProductTypes")
                        .WithMany("TargetCategoryProductTypes")
                        .HasForeignKey("ProductTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnswerUA.Models.TargetCategories", "TargetCategories")
                        .WithMany("TargetCategoryProductTypes")
                        .HasForeignKey("TargetCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTypes");

                    b.Navigation("TargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.Brand", b =>
                {
                    b.Navigation("BrandTargetCategories");
                });

            modelBuilder.Entity("AnswerUA.Models.Orders", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AnswerUA.Models.ProductTypes", b =>
                {
                    b.Navigation("Subcategories");

                    b.Navigation("TargetCategoryProductTypes");
                });

            modelBuilder.Entity("AnswerUA.Models.Subcategories", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("AnswerUA.Models.TargetCategories", b =>
                {
                    b.Navigation("TargetCategoryProductTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
