services:
  answer_ua:
    image: lego923/answer_ua:latest # eb24da6a5511          # або твій тег (lego923/answer_ua:latest)
    container_name: answer_ua_up
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ASPNETCORE_ENVIRONMENT: "Development"

      # 🔹 Підключення двох SQLite баз
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/app.db"
      ConnectionStrings__AnswerDatabase: "Data Source=/app/data/Answear.db"

      # 🔹 OAuth ключі (можеш замінити на реальні)
      Authentication__Microsoft__ClientId: "test"
      Authentication__Microsoft__ClientSecret: "test"
      Authentication__Google__ClientId: "test"
      Authentication__Google__ClientSecret: "test"
      Authentication__Facebook__ClientId: "test"
      Authentication__Facebook__ClientSecret: "test"

    volumes:
      # 🔹 Папка на сервері, де зберігаються твої бази
      - ~/answer_au/data:/app/data
    networks:
      - webnet
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certs:/etc/letsencrypt:rw
    depends_on:
      - answer_ua
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
