name: .NET CI
on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

jobs:
    build:
        runs-on: ubuntu-latest #self-hosted
        env:
          # Підключення до SQLite
          ConnectionStrings__DefaultConnection: "Data Source=app.db"
          # Підключення до другої SQLite бази
          ConnectionStrings__AnswerDatabase: "Data Source=Answear.db"
        
        steps:
            - name: checkout code
              uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'
             
            - name: Check SQLite database file
              run: |
                ls -l app.db || echo "⚠️ app.db not found — ensure it's in the repo root"
            
            - name: Restore dependencies
              run: dotnet restore answer_ua.sln

            - name: Build
              run: dotnet build answer_ua.sln --no-restore --configuration Release

            - name: Test
              run: dotnet test answer_ua.sln --no-build --configuration Release --verbosity normal --logger trx
